%%
%% Autogenerated by Thrift Compiler (0.9.0)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(ecometRouter_thrift).
-behaviour(thrift_service).


-include("ecometRouter_thrift.hrl").

-export([struct_info/1, function_info/2]).

struct_info('i am a dummy struct') -> undefined.
%%% interface
% send(This, AppId, Id, Msg)
function_info('send', params_type) ->
  {struct, [{1, string},
          {2, string},
          {3, string}]}
;
function_info('send', reply_type) ->
  oneway_void;
function_info('send', exceptions) ->
  {struct, []}
;
% get_online_count(This, AppId)
function_info('get_online_count', params_type) ->
  {struct, [{1, string}]}
;
function_info('get_online_count', reply_type) ->
  i32;
function_info('get_online_count', exceptions) ->
  {struct, []}
;
% get_online_ids(This, AppId)
function_info('get_online_ids', params_type) ->
  {struct, [{1, string}]}
;
function_info('get_online_ids', reply_type) ->
  {list, string};
function_info('get_online_ids', exceptions) ->
  {struct, []}
;
function_info(_Func, _Info) -> no_function.

